# TensorFlow Tutorial

뉴럴넷과 CNN에 대해 기본적인 강의를 듣고 기초지식을 가지고 있다는 가정하에 진행되는 튜토리얼입니다.

In [1]:
import tensorflow as tf
import numpy as np

Basic Code

In [2]:
a = tf.constant([2],dtype=tf.float32)
b = tf.constant([3],dtype=tf.float32)
c = tf.constant([4],dtype=tf.float32)

op = a*b+c
# op = tf.add(tf.multiply(a,b), c)

sess = tf.Session()
result = sess.run(op)
print(result)
sess.close()

[ 10.]


tf.constant

In [3]:
# Constant 1-D Tensor populated with value list.
tensor1 = tf.constant([1, 2, 3, 4, 5, 6, 7]) # [1 2 3 4 5 6 7]

# Constant 2-D tensor populated with scalar value -1.
tensor2 = tf.constant(-1.0, shape=[2, 3]) # [[-1. -1. -1.], [-1. -1. -1.]]

sess = tf.Session()
print(sess.run(tensor1))
print(sess.run(tensor2))
print(tensor1)
print(tensor2)
sess.close()

[1 2 3 4 5 6 7]
[[-1. -1. -1.]
 [-1. -1. -1.]]
Tensor("Const_3:0", shape=(7,), dtype=int32)
Tensor("Const_4:0", shape=(2, 3), dtype=float32)


tf.placeholder

In [4]:
input_data = [1,2,3,4,5]

x = tf.placeholder(dtype=tf.float32)
k = tf.constant(2, dtype=tf.float32)
y = x * k

sess = tf.Session()
result = sess.run(y, feed_dict={x:input_data})

print(result)

[  2.   4.   6.   8.  10.]


tf.Variable

In [ ]:
input_data = [1,2,3,4,5]

x = tf.placeholder(dtype=tf.float32)
W = tf.Variable([2],dtype=tf.float32)
y = W*x

sess = tf.Session()
result = sess.run(y,feed_dict={x:input_data})

print(result)

In [6]:
input_data = [1,2,3,4,5]

x = tf.placeholder(dtype=tf.float32)
W = tf.Variable([10],dtype=tf.float32)
W = W.assign_add([10.0])
y = W*x

sess = tf.Session()

init = tf.global_variables_initializer()
sess.run(init)

result = sess.run(y, feed_dict={x:input_data})

print(result)

[  20.   40.   60.   80.  100.]


# MNIST w/ Single Layer Perceptron

MNIST Data

In [7]:
import tensorflow as tf
import numpy as np
import scipy.misc

In [8]:
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets('MNIST_data/', one_hot=True)

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz


In [9]:
mnist.train.images.shape

(55000, 784)

In [10]:
scipy.misc.toimage(mnist.train.images[999].reshape((28,28)))

In [11]:
mnist.train.labels[999]

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.])

In [ ]:
images = tf.placeholder(shape=[None, 784], dtype=tf.float32)
labels = tf.placeholder(shape=[None, 10], dtype=tf.float32)

W = tf.Variable(tf.truncated_normal([784, 10], stddev=0.1))
b = tf.Variable(tf.zeros([10]))

In [ ]:
logit = tf.nn.softmax(tf.matmul(images, W) + b)
loss = -tf.reduce_sum(labels*tf.log(logit))

In [ ]:
train_op = tf.train.GradientDescentOptimizer(0.01).minimize(loss)

In [ ]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [ ]:
for i in range(1000):
    batch_xs, batch_ys = mnist.train.next_batch(100)
    sess.run(train_op, feed_dict={images: batch_xs, labels: batch_ys})

Accuracy

In [ ]:
correct_prediction = tf.equal(tf.argmax(logit, axis=1), tf.argmax(labels, axis=1))
acc = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

In [ ]:
print(sess.run(acc, feed_dict={images: mnist.train.images, labels: mnist.train.labels}))

In [ ]:
print(sess.run(acc, feed_dict={images: mnist.test.images, labels: mnist.test.labels}))

각각 Training Set Accuracy, Test Set Accuracy 입니다.

# Practice MLP

In [ ]:
import tensorflow as tf
import numpy as np
import scipy.misc

In [ ]:
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets('MNIST_data/', one_hot=True)

In [ ]:
images = tf.placeholder(shape=[None, 784], dtype=tf.float32)
labels = tf.placeholder(shape=[None, 10], dtype=tf.float32)
# W = tf.Variable(tf.zeros([784, 10]))
W1 = tf.Variable(tf.truncated_normal([784, 100], stddev=0.1))
b1 = tf.Variable(tf.zeros([100]))
W2 = tf.Variable(tf.truncated_normal([100, 10], stddev=0.1))
b2 = tf.Variable(tf.zeros([10]))

In [ ]:
out1 = tf.nn.relu(tf.matmul(images, W1) + b1)
logit = tf.nn.softmax(tf.matmul(out1, W2) + b2)
# loss = -tf.reduce_sum(labels*tf.log(logit))
# loss = tf.nn.softmax_cross_entropy_with_logits()
loss = tf.reduce_sum(
    tf.nn.softmax_cross_entropy_with_logits_v2(labels=labels, logits=logit)
)

In [ ]:
train_op = tf.train.GradientDescentOptimizer(0.01).minimize(loss)

In [ ]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [ ]:
for i in range(1000):
    batch_xs, batch_ys = mnist.train.next_batch(100, shuffle=True)
    _, batch_loss = sess.run([train_op, loss], feed_dict={images: batch_xs, labels: batch_ys})
print(batch_loss)

loss

In [ ]:
acc = tf.reduce_mean(tf.cast(
    tf.equal(tf.argmax(logit, axis=1), tf.argmax(labels, axis=1)),
    tf.float32))

In [ ]:
print(sess.run(acc, feed_dict={images: mnist.train.images, labels: mnist.train.labels}))

In [ ]:
print(sess.run(acc, feed_dict={images: mnist.test.images, labels: mnist.test.labels}))

# MNIST w/ CNN

In [ ]:
import tensorflow as tf
import numpy as np
import scipy.misc

In [ ]:
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets('MNIST_data/', one_hot=True)

In [ ]:
def weight_variable(shape):
    initial = tf.truncated_normal(shape, stddev=0.1)
    return tf.Variable(initial)

def bias_variable(shape):
    initial = tf.constant(0.1, shape=shape)
    return tf.Variable(initial)

In [ ]:
def conv(x, W):
    return tf.nn.conv2d(x, W, strides=[1, 1, 1, 1], padding='SAME')

def max_pool(x):
    return tf.nn.max_pool(x, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1], padding='SAME')

In [ ]:
images = tf.placeholder(shape=[None, 784], dtype=tf.float32)
reshape_images = tf.reshape(images, [-1, 28, 28, 1])

labels = tf.placeholder(shape=[None, 10], dtype=tf.float32)

In [ ]:
W_conv1 = weight_variable([5,5,1,32])
b_conv1 = bias_variable([32])

W_conv2 = weight_variable([5,5,32,64])
b_conv2 = bias_variable([64])

W_fc1 = weight_variable([7*7*64, 1024])
b_fc1 = bias_variable([1024])

W_fc2 = weight_variable([1024, 10])
b_fc2 = bias_variable([10])

In [ ]:
conv_layer1 = tf.nn.relu(conv(reshape_images, W_conv1) + b_conv1)
pool_layer1 = max_pool(conv_layer1)

conv_layer2 = tf.nn.relu(conv(pool_layer1, W_conv2) + b_conv2)
pool_layer2 = max_pool(conv_layer2)

pool2_flat = tf.reshape(pool_layer2, [-1, 7*7*64])
fc_layer1 = tf.nn.relu(tf.matmul(pool2_flat, W_fc1) + b_fc1)

keep_prob = tf.placeholder(tf.float32)
drop_out = tf.nn.dropout(fc_layer1, keep_prob)

logit = tf.matmul(drop_out, W_fc2) + b_fc2

In [ ]:
loss = tf.reduce_mean(
    tf.nn.softmax_cross_entropy_with_logits_v2(labels=labels, logits=logit)
)
train_op = tf.train.AdamOptimizer(1e-4).minimize(loss)
correct_prediction = tf.equal(tf.argmax(logit, 1), tf.argmax(labels, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

max_epoch = 500
# with tf.Session() as sess:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for i in range(max_epoch):
    batch = mnist.train.next_batch(50, shuffle=True)
    sess.run(train_op, 
         feed_dict={images: batch[0], labels: batch[1], keep_prob: 0.5}
    )
    train_acc = sess.run(accuracy,
        feed_dict={images: batch[0], labels: batch[1], keep_prob: 1.0}
    )
    print('step %d, training accuracy %g' % (i, train_acc))
    if i % 100 == 0:
        test_acc = sess.run(accuracy, 
             feed_dict={images: mnist.test.images, labels: mnist.test.labels, keep_prob: 1.0}
        )
        print('test accuracy %g' % test_acc)
test_acc = sess.run(accuracy, 
     feed_dict={images: mnist.test.images, labels: mnist.test.labels, keep_prob: 1.0}
)
print('test accuracy %g' % test_acc)

# Prediction w/ CNN

In [ ]:
input_data = mnist.train.images[999:1000]
print(np.argmax(mnist.train.labels[999]))
scipy.misc.toimage(input_data[0].reshape((28,28)))

In [ ]:
pred = tf.argmax(logit, 1)
result = sess.run(pred, feed_dict={images: input_data, keep_prob: 1.0})
print('Prediction Result: {}'.format(result[0]))

# Tensorboard w/ CNN

In [ ]:
import tensorflow as tf
import numpy as np
import scipy.misc

In [ ]:
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets('MNIST_data/', one_hot=True)

In [ ]:
def weight_variable(shape, name='weights'):
    initial = tf.truncated_normal(shape, stddev=0.1)
    return tf.Variable(initial, name=name)

def bias_variable(shape, name='biases'):
    initial = tf.constant(0.1, shape=shape)
    return tf.Variable(initial, name=name)

In [ ]:
def conv(x, W, name='conv'):
    with tf.name_scope(name) as scope:
        return tf.nn.conv2d(x, W, strides=[1, 1, 1, 1], padding='SAME')

def max_pool(x, name='max_pool'):
    with tf.name_scope(name) as scope:
        return tf.nn.max_pool(x, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1], padding='SAME')

In [ ]:
images = tf.placeholder(shape=[None, 784], dtype=tf.float32)
reshape_images = tf.reshape(images, [-1, 28, 28, 1])

labels = tf.placeholder(shape=[None, 10], dtype=tf.float32)

In [ ]:
W_conv1 = weight_variable([5,5,1,32])
b_conv1 = bias_variable([32])

W_conv2 = weight_variable([5,5,32,64])
b_conv2 = bias_variable([64])

W_fc1 = weight_variable([7*7*64, 1024])
b_fc1 = bias_variable([1024])

W_fc2 = weight_variable([1024, 10])
b_fc2 = bias_variable([10])

In [ ]:
conv_layer1 = tf.nn.relu(conv(reshape_images, W_conv1) + b_conv1)
pool_layer1 = max_pool(conv_layer1)

conv_layer2 = tf.nn.relu(conv(pool_layer1, W_conv2) + b_conv2)
pool_layer2 = max_pool(conv_layer2)

pool2_flat = tf.reshape(pool_layer2, [-1, 7*7*64])

with tf.name_scope('fc_layer') as scope:
    fc_layer1 = tf.nn.relu(tf.matmul(pool2_flat, W_fc1) + b_fc1)

with tf.name_scope('fc_layer') as scope:
    keep_prob = tf.placeholder(tf.float32)
    drop_out = tf.nn.dropout(fc_layer1, keep_prob)
    logit = tf.matmul(drop_out, W_fc2) + b_fc2

In [ ]:
loss = tf.reduce_mean(
    tf.nn.softmax_cross_entropy_with_logits_v2(labels=labels, logits=logit)
)
train_op = tf.train.AdamOptimizer(1e-4).minimize(loss)
correct_prediction = tf.equal(tf.argmax(logit, 1), tf.argmax(labels, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
tf.summary.image('images', reshape_images)
tf.summary.scalar('xentropy', loss)
tf.summary.scalar('accuracy', accuracy)
merged = tf.summary.merge_all()

max_epoch = 500
# with tf.Session() as sess:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
test_writer = tf.summary.FileWriter('./test', sess.graph)
for i in range(max_epoch):
    batch = mnist.train.next_batch(50, shuffle=True)
    sess.run(train_op, 
         feed_dict={images: batch[0], labels: batch[1], keep_prob: 0.5}
    )
    train_acc = sess.run(accuracy,
        feed_dict={images: batch[0], labels: batch[1], keep_prob: 1.0}
    )
    print('step %d, training accuracy %g' % (i, train_acc))
    if i % 100 == 0:
        test_acc, summary = sess.run([accuracy, merged], 
             feed_dict={images: mnist.test.images, labels: mnist.test.labels, keep_prob: 1.0}
        )
        print('test accuracy %g' % test_acc)
        test_writer.add_summary(summary, i)
test_acc, summary = sess.run([accuracy, merged], 
     feed_dict={images: mnist.test.images, labels: mnist.test.labels, keep_prob: 1.0}
)
print('test accuracy %g' % test_acc)
test_writer.add_summary(summary, i)

In [ ]:
summary